version: '3.5'
services:
  bareksa-news:
    image: bareksa-news
    ports:
      - 8080:8080
    links:
      - postgres
      - pgadmin
    restart: always
    networks:
      - postgres
      - redis
  postgres:
    image: postgres
    container_name: postgres_bareksa
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - postgres
    volumes:
      - ./db-seeder.sql:/docker-entrypoint-initdb.d/db-seeder.sql
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
    networks:
      - redis
networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
volumes:
  pgadmin:
  db:
  cache:
